### ISSUE TITLE
滑动viewpager导致程序崩溃

### ISSUE THREAD

**Issue by mycold** [qkxyjren/LikeView#9]
09-20 10:10:37.021 12848-12848/com.jaren.likeview E/MessageQueue-JNI: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.ProgressBar$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/tb_s_bar. Make sure other views do not use the same id.
        at android.view.View.onRestoreInstanceState(View.java:13979)
        at android.view.View.dispatchRestoreInstanceState(View.java:13955)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3014)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3020)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3020)
        at android.view.View.restoreHierarchyState(View.java:13933)
        at android.support.v4.app.Fragment.restoreViewState(Fragment.java:415)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1454)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:792)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2124)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1996)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2508)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1781)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2819)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2465)
        at android.view.View.dispatchPointerEvent(View.java:8811)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4727)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4584)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4083)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4136)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4102)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4239)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4110)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4296)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4083)
    	at android.view.ViewRootImp

**Comment by qkxyjren** [comment]
This view's id is id/tb_s_bar. Make sure other views do not use the same id.有重复使用这个id吗，重命名tb_s_bar试试

**Comment by qkxyjren** [comment]
@mycold 
This view's id is id/tb_s_bar. Make sure other views do not use the same id.有重复使用这个id吗，重命名tb_s_bar试试

**Comment by qkxyjren** [comment]
@mycold 麻烦同步代码再试一下是否还有问题

**Comment by mycold** [comment]
再提个小建议：取消点赞的操作必须是在点赞动画执行完成之后才有效，这个可以改成立即取消吗，或者暴露个接口取消执行动画

**Comment by qkxyjren** [comment]
> 再提个小建议：取消点赞的操作必须是在点赞动画执行完成之后才有效，这个可以改成立即取消吗，或者暴露个接口取消执行动画

可以用这个方法：mLikeView.setCheckedWithoutAnimator(false);//无动画取消选择
